# This file is not needed for GitHub Pages deployment
# GitHub Pages uses GitHub Actions workflow instead
# You can delete this file if you're only using GitHub Pages

[build]
  command = "npm install && npm run build"
  publish = "dist"
  base = "/"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  CI = "true"

[build.processing]
  skip_processing = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"